### PR TITLE
do not run stop_app when _stopping is true

### PR DESCRIPTION
**Pull request by knorth55**
when `stop_app` service is called, `stop_app` can be called twice from `stop_app` service and `app_monitor`.
this PR add `_stopping` attribute, and do not run `stop_app` from `app_monitor` when `_stopping` is true.

### CODE REVIEW

**Comment by knorth55** [comment]
@708yamaguchi can you review this PR?

**Comment by 708yamaguchi** [comment]
Using a value of True/None for `self._stopping` seems unnatural to me.
Should it be True/False?

**Comment by knorth55** [comment]
it is a natural thing, i think.
`None` means nothing, and `False` means negative.
In this case, the app stops, so `_stopping` should be nothing `None` as initialization.

**Comment by 708yamaguchi** [comment]
Thank you for your explanation.

True/False is not your mistake, then it's OK.

**Comment by knorth55** [comment]
@k-okada can you review and merge this PR?
without this PR, `app_manager` runs `stop_app` twice and run `plugins` twice in parallel unintentionally.

**Comment by knorth55** [comment]
@k-okada kindly ping. can you review and merge this PR?

**Review by k-okada — APPROVED** [review]

**Pull request merged**
