### PR TITLE
fix to install appmaster

### LINKED ISSUE #1: missing appmaster in install
@TheDash 
I wonder why this repository has `appmaster` executable in `bin` directory, which is omitted to install in CMakeLists.txt.
This program is indispensable for users.

### PR DESCRIPTION
**Pull request by furushchev**
this fixes #1, please merge and release ASAP since hydro is almost EOL

### CODE REVIEW

**Comment by k-okada** [comment]
+1

**Comment by UltronDestroyer** [comment]
Does this mean shadow fixed build farm will shut down?

In addition, I have the capability to build and deploy PR2 ROS packages from the clearpath repo using buildbot.

**Comment by trainman419** [comment]
Yes; the main buildfarm, including shadow-fixed, will stop building Hydro packages one Hydro is EOL (as per recent announcements on the ros-release mailing list).

**Comment by k-okada** [comment]
link -> http://lists.ros.org/pipermail/ros-release/2015-July/004658.html

## 

◉ Kei Okada

**Pull request merged**
