### PR TITLE
set stopped true in app timeout

### PR DESCRIPTION
**Pull request by knorth55**
when app is `timeout`, `stopped` param in `plugin_context` is not set as `True`.
This PR correctly set `stopped` param as `True` when app is timeout in `plugin_context`.

### CODE REVIEW

**Comment by 708yamaguchi** [comment]
In my understanding, with this PR, if the app is terminated due to a timeout, we will get an email saying "the demo has failed!"

**Review by 708yamaguchi — APPROVED** [review]

**Comment by knorth55** [comment]
@k-okada this is my fault, but can you merge this PR? this PR correctly handle `stopped` value for `app_manager_plugins`

**Review by k-okada — APPROVED** [review]
LGTM

**Comment by knorth55** [comment]
Thank you!

**Pull request merged**
