### PR TITLE
Support loading installed apps from export tags

### PR DESCRIPTION
**Pull request by furushchev**
## Summary
This PR is for adding feature to load application directory using `<export>` tag in `package.xml`.
#6 should be applied first.

Currently, a directory for installed apps must be specified manually via `--applist` option on launch `app_manager`.
This PR adds support to load app directories defined as `<export>` tag in `package.xml` for each package.

For example, if applications are located in `pkgA/apps`, `pkgB/apps` and `pkgC/apps` directoies, `app_manager` must be run as follows:

```bash
rosrun app_manager app_manager --applist pkgA/apps;pkgB/apps;pkgC/apps
```

After this PR, you can skip the `--applist` option and add `<export>` tag instead:

```xml
<!-- pkgA/packtge.xml -->
<packge>
  ...
  <export>
    <app_manager app_dir="${prefix}/apps"/>
  </export>
</package>
```

And do the same thing to `pkgB/package.xml` and `pkgC/package.xml`, and then run `app_manager`:

```bash
rosrun app_manager app_manager
```

## Changes

- All commits in #6 
- Added feature to load app directories from `<export>` tag
- Added README
- Added sample launch file

### CODE REVIEW

**Review by v4hn — APPROVED** [review]
I just looked through the changes that are not part of #6 and they look good too.

I don't have a setup to test the new functionality over here, but I approve.

**Comment by furushchev** [comment]
@v4hn Thanks for this review too!

I noticed that there is one possible problem regarding the platform.
Current implementation loads all available apps specified in `<export>` tags including apps for other platforms.
Since there is already the information about the platform in each app, we can use this for excluding apps for other platforms.
I will fix this pull request in a moment...

**Comment by furushchev** [comment]
OK I updated the codes and readme.
Now only apps for `pr2` shows up if we set `/robot/type` to `pr2`, if no platform is specified, all apps are available.

**Comment by v4hn** [comment]
The additional check makes sense and looks good. I still improve.
Now this only waits for a second reviewer...

**Review by k-okada — COMMENTED** [review]
@708yamaguchi , @Affonso-Gui can you test these new features on our Fetch robot?

**Comment by furushchev** [comment]
FYI: @708yamaguchi @Affonso-Gui I personally tested by using the commit: https://github.com/furushchev/jsk_robot/commit/1ae03d9b56b7ba33cf2db01595fce668f829b17e#diff-21e82f97fe6bc70e6635073d28407c3d

**Comment by 708yamaguchi** [comment]
@k-okada @furushchev 
I tested this Pull Request with this app(https://github.com/jsk-ros-pkg/jsk_robot/pull/961), and it worked correctly.

**Comment by k-okada** [comment]
ok, released into lunar(https://github.com/ros/rosdistro/pull/18979) and meldoic (https://github.com/ros/rosdistro/pull/18982)
pleas check them and if that is ok, we'll release into indigo kinetic @furushchev @708yamaguchi

**Comment by 708yamaguchi** [comment]
@k-okada @furushchev 
fetchやPR2をlunar, melodicにしてチェックすればいいということでしょうか？

**Comment by v4hn** [comment]
Please keep posts here in English.

> fetchやPR2をlunar, melodicにしてチェックすればいいということでしょうか？
> また、岡田先生の貼られた2つのリンクは一体どういうものでしょうか？
> https://github.com/gbiggs/rtsprofile
> ros/rosdistro#18982

**Comment by 708yamaguchi** [comment]
@v4hn 
I am very sorry that I forget this is public repository.

@k-okada 
Does

> pleas check them and if that is ok, we'll release into indigo kinetic @furushchev @708yamaguchi

mean that I should check this feature with `fetch` and `PR2` of `lunar` and `melodic`?

**Comment by k-okada** [comment]
> mean that I should check this feature with fetch and PR2 of lunar and melodic?

no, if you can run app_manger on your local machine, then install lunar version on 16.04, if you need to run app_manager on robot, 
```
apt download ros-lunar-app-manager
dpkg -x ros-lunar-app-manager ~/catkin_ws/
```
and update ROS_PACKAGE_PATH, PATH and PYTHONPATH  or
something like
 ```
mv ~/catkin_ws/opt/ros/lunar/* ~/catkin_ws/devel/
```

**Comment by k-okada** [comment]
@furushchev @708yamaguchi please check this PR very carefully, I have noticed some regression in this changes (see #10)

**Pull request merged**
