### PR TITLE
fix readme

### PR DESCRIPTION
**Pull request by knorth55**
current readme.md is not well-formatted.

### CODE REVIEW

**Review by v4hn — APPROVED** [review]
True, thanks.

**Comment by v4hn** [comment]
Assuming you plan to stay around for a while longer, maybe you should talk to @k-okada on taking on maintainership for the `app_manager` repositories. :wink:

**Comment by knorth55** [comment]
@v4hn I'm sorry to bother you again and again.
That's true, I will talk with @k-okada .

**Comment by v4hn** [comment]
Sending open source contributions is never a bother!
I'm happy to see you working on/with these packages!

You just have to accept possibly long timeouts by maintainers...
Today,  I would say you were quite lucky :sunglasses: 

I clearly support you having maintainer level access to the `app_manager` related repositories.
@k-okada Could you talk to @knorth55 and possibly create a team with the right permissions?

**Pull request merged**
