### PR TITLE
add exit_codes in app_monitor

### PR DESCRIPTION
**Pull request by knorth55**
this PR fixes issue reported in https://github.com/PR2/app_manager/pull/55#discussion_r871590911 .
#55 removes exit_codes check in `app_monitor`.
this PR add the exit_code check again.
This exit code check is needed when app is correctly done and required node exits by itself.

### CODE REVIEW

**Review by Affonso-Gui — CHANGES_REQUESTED** [review]
Nice catch!

I was planning on leaving the exit_code management to `__stop_current` (https://github.com/PR2/app_manager/blob/kinetic-devel/src/app_manager/app_manager.py#L538-L548), but apparently required nodes are not added to the dead_list: https://github.com/ros/ros_comm/blob/f5fa3a168760d62e9693f10dcb9adfffc6132d22/tools/roslaunch/src/roslaunch/pmon.py#L566-L574

Instead, when a required node dies the process manager just shutdowns and cleans everything, meaning we can only access its exit code if we are able to catch it during the shutdown. Probably the right way to do this is to add a listener to the process monitor, but the time interval of 0.1s also seems to be working fine https://github.com/PR2/app_manager/blob/kinetic-devel/src/app_manager/app_manager.py#L643

I would, however, still like to suggest a few style changes to better match the rest of the `app_manager` function. Created a PR in https://github.com/knorth55/app_manager/pull/1

**Review by Affonso-Gui — APPROVED** [review]

**Comment by k-okada** [comment]
@Affonso-Gui @knorth55 can we create test code, to prevent future regressions?

**Comment by knorth55** [comment]
@k-okada I added the test to check `context` in `app_manager_plugin`.
#57 may drop the test because of the regression and this PR may pass the test.

**Comment by knorth55** [comment]
@k-okada I add the test.
The test failed in #57  as expected, and this PR passed the test.
Please merge this PR.

**Comment by knorth55** [comment]
@k-okada kindly ping. can you merge this PR? This is a critical bug because app_manager reports wrong exit code.
I fixed the issue and add the test.

**Comment by knorth55** [comment]
Thank you!

**Pull request merged**
