### PR TITLE
Cleanup unused files

### PR DESCRIPTION
**Pull request by furushchev**
- Removed automatically generated files/dirs (`msg_gen`, `srv_gen`, `.pyc` files, `Makefile`, etc.)
- Moved `rosget` from scripts to bin directory since it is executable
- Fixed `install` section in `CMakLists.txt`
- Added tests

### CODE REVIEW

**Review by v4hn — APPROVED** [review]
I missed your work here before, sorry.

This package was probably not used in quite a while...

Thank you for the cleanup, I looked through the changes and approve.

**Comment by furushchev** [comment]
@v4hn Thank you for the review! :+1:

**Review by k-okada — APPROVED** [review]
overall , it ok. 
I think moving files to `bin/` directory just because of they are executable seems strange. Because catkin package is not expect `bin/` directory (
http://wiki.ros.org/Packages) and I think they comes from old rosmake fashion ( 
http://wiki.ros.org/rosbuild/Packages , http://wiki.ros.org/ja/Packages)

**Comment by furushchev** [comment]
@k-okada I did not know that the package structure is documented in detail. I got it now.

**Pull request merged**
