### PR TITLE
set current_app None when start failed

### PR DESCRIPTION
**Pull request by knorth55**
`_set_current_app` `None` when start failed.
this prevents `app_manager` hanging when launching is failed.

related: #42 

cc @tkmtnt7000

### CODE REVIEW

**Comment by knorth55** [comment]
@k-okada this PR passed CI. can you merge this PR?
this PR fixes the bug and enables to run new app after previous app failed starting.

**Comment by k-okada** [comment]
@tkmtnt7000 did you check this PR? I have created test code https://github.com/PR2/app_manager/pull/46/commits/160b760773e96837b373500997d1fc80a33c371c but it fails with 

```
ROS_MASTER_URI=http://p51s:35265/
[talker_p51s_10605_7045131409288767794-1] process has died without exit code [pid -1, cmd no_command /opt/ros/melodic/share/rospy_tutorials/001_talker_listener/talker.py __name:=talker_p51s_10605_7045131409288767794 __log:=/home/k-okada/.ros/log/024a9112-3bbe-11ec-be04-00bb605aa0af/talker_p51s_10605_7045131409288767794-1.log].
log file: /home/k-okada/.ros/log/024a9112-3bbe-11ec-be04-00bb605aa0af/talker_p51s_10605_7045131409288767794-1*.log
[INFO] [1635844786.643917]: Unregistering (/robot/application/app_status,http://p51s:39975/) from master http://localhost:11312
[INFO] [1635844786.646403]: Unregistering (/robot/app_list,http://p51s:39975/) from master http://localhost:11312
[INFO] [1635844786.648763]: Unregistering service (/robot/start_app,rosrpc://p51s:38943) from master http://localhost:11312
[INFO] [1635844786.650937]: Unregistering service (/robot/stop_app,rosrpc://p51s:38943) from master http://localhost:11312
[INFO] [1635844786.652934]: Unregistering service (/robot/list_apps,rosrpc://p51s:38943) from master http://localhost:11312
[ERROR] [1635844786.737791]: Error processing request: 'NoneType' object has no attribute 'stop'
['Traceback (most recent call last):\n', '  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 632, in _handle_request\n    response = convert_return_to_response(self.handler(request), self.response_class)\n', '  File "/home/k-okada/catkin_ws/ws_roswww/src/app_manager/src/app_manager/app_manager.py", line 443, in handle_start_app\n    self._stop_current()\n', '  File "/home/k-okada/catkin_ws/ws_roswww/src/app_manager/src/app_manager/app_manager.py", line 466, in _stop_current\n    self._interface_sync.stop()\n', "AttributeError: 'NoneType' object has no attribute 'stop'\n"]

```


and need to add https://github.com/PR2/app_manager/pull/46/commits/bc1d608061543a571dbd22f653c1e9f2849de576

**Comment by knorth55** [comment]
@k-okada thank you for debugging. you are right. I didn't know that we need except in this case.

```python
In [1]: try:
   ...:     raise ValueError
   ...: finally:
   ...:     print('hoge')
   ...:     
hoge
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-a2881e0564ce> in <module>()
      1 try:
----> 2     raise ValueError
      3 finally:
      4     print('hoge')
      5 

ValueError: 

In [2]: try:
   ...:     raise ValueError
   ...: except Exception:
   ...:     pass
   ...: finally:
   ...:     print('hoge')
   ...:     
hoge
```

**Comment by tkmtnt7000** [comment]
@k-okada
Thank you for debugging. I think we need to add bc1d608, too.

**Comment by k-okada** [comment]
closed via #46

**Pull request closed without merging**
